[package]
name = "markdown_preview"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lib]
path = "src/markdown_preview.rs"

[features]
test-support = []

[dependencies]
anyhow.workspace = true
editor = { path = "../editor" }
gpui = { path = "../gpui" }
language = { path = "../language" }
lazy_static.workspace = true
log.workspace = true
menu = { path = "../menu" }
project = { path = "../project" }
pretty_assertions.workspace = true
pulldown-cmark.workspace = true
theme = { path = "../theme" }
ui = { path = "../ui" }
util = { path = "../util" }
workspace = { path = "../workspace" }

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
