[package]
name = "markdown_preview"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lib]
path = "src/markdown_preview.rs"

[features]
test-support = []

[dependencies]
editor = { path = "../editor" }
gpui = { path = "../gpui" }
language = { path = "../language" }
menu = { path = "../menu" }
project = { path = "../project" }
theme = { path = "../theme" }
ui = { path = "../ui" }
util = { path = "../util" }
workspace = { path = "../workspace" }
rich_text = { path = "../rich_text" }

anyhow.workspace = true
lazy_static.workspace = true
log.workspace = true
pulldown-cmark.workspace = true

[dev-dependencies]
editor = { path = "../editor", features = ["test-support"] }
